### ISSUE TITLE
请问下怎么安装实用这个程序

### ISSUE THREAD

**Issue by banduoba** [Crazy-MT/notification_listener#1]
请问这个程序是可以监控mac电脑上的通知中心的信息么,请问怎么安装下呢,监控的通知中心信息支持wehook么

**Comment by Crazy-MT** [comment]
对的，这个程序是监控 mac 电脑的通知中心的消息。该仓库是一个可运行的 flutter 工程，电脑安装最新 flutter 的运行环境，然后可以运行对应的 mac 端程序即可。可以根据自己的需要修改 flutter 代码，完成 webhook 之类的功能哈。
